version: 'latest'
services:
  swift-cloud-demo-db:
    image: postgres:latest
    container_name: swift-cloud-demo-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command: postgres -c port=${DB_PORT}
    networks:
     - app-network
  
  swift-cloud-demo-service:
    build:
      context: ./
      dockerfile: Dockerfile.demo
    image: swift-backend:latest
    container_name: swift-backend
    depends_on:
      - swift-cloud-demo-db
    tty: true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network
    restart: always
    command: ["sh", "-c", "bun prisma:dev:deploy && bun start:prod"]
    
networks:
  app-network:
    driver: bridge